spring:
  application:
    name: observetask-user-service
  datasource:
    url: jdbc:postgresql://host.minikube.internal:5432/observetask_db
    username: observetask_dev
    password: dev_password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: observetask_userservice

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
