spring:
  application:
    name: observetask-user-service
  
  # Enable Virtual Threads (Java 21 feature)
  threads:
    virtual:
      enabled: true

  # Database Configuration
  datasource:
    url: jdbc:postgresql://host.minikube.internal:5432/observetask_db
    username: observetask_user_svc
    password: user_service_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: observetask_users
        format_sql: true
    defer-datasource-initialization: false

  # Flyway Configuration
  flyway:
    schemas: observetask_users
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  # Kafka Configuration
  kafka:
    bootstrap-servers: host.minikube.internal:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.observetask.userservice.event"

  # Redis Configuration
  data:
    redis:
      host: host.minikube.internal
      port: 6379
      database: 1
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  server:
    port: 8081
  metrics:
    export:
      prometheus:
        enabled: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:ObserveTask-Super-Secret-Key-For-Development-Only-2024}
  access-token-expiration: 900000    # 15 minutes
  refresh-token-expiration: 604800000 # 7 days
  secret: "your-rsa-private-key-or-secret"
  access-token-expiration: 900000    # 15 minutes in milliseconds
  refresh-token-expiration: 604800000 # 7 days in milliseconds
  issuer: "observetask"

# Logging Configuration
logging:
  level:
    root: INFO
    com.observetask.userservice: DEBUG
    org.springframework.security: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"